### ISSUE TITLE
Falks Skript wieder zum Laufen bringen

### ISSUE THREAD

**Issue by knofterle** [knofterle/FRAXSILVA_R#1]
Ich habe das Problem gefunden:
bei Zeile 108 schreibst du:

all_points <- data.frame(
	nr = c(data_tree_scho$nr),
	x = c(data_tree_scho$x),
	y = c(data_tree_scho$y),
	art = c(data_tree_scho$art),
	dia = c(data_tree_scho$dmess))

Und das ist das Problem sozusagen, ich weiß, dass das bei mir auch so steht aber in meinem Skript brauchte ich erstmal nur ein paar Bäume als Bildhintergrund. Vollständigkeit war egal.
Es gibt jetzt eine Spalte "art" und eine "art.stammv". Die Spalte "art" kommt ursprünglich aus der Tabelle "baum". In "art" ist jetzt aber nicht mehr alles drin, weil zum Beispiel die Kanzel nur noch in der Tabelle "stammv" vorkommt aber nicht mehr in "baum", und somit nur noch bei "art.stamv" auftaucht. 
Ich würde dir empfehlen das Skript generate plotmap und plotdistribution weg zu lassen. Und statt dessen ab load.data.tree selber mit dem dataframe data_tree_scho weiter zu machen

**Comment by wurzel1** [comment]
"art" durch "art.stammv" klappt!
